name: Java CD with Docker

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Docker Container on Remote Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
          APP_PORT: 8080
        run: |
               mkdir -p ~/.ssh
               echo "${SSH_PRIVATE_KEY}" > ~/.ssh/github_rsa
               chmod 400 ~/.ssh/github_rsa
               ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
               ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} << "EOF"
               cd mayo
               docker stop mayo-client || true && docker rm mayo-client || true &&
               docker run --network host -d --name mayo-client -p ${APP_PORT}:${APP_PORT} mayo-client
               sleep 10
               docker image prune -a -f
               EOF